- name: set manage zookeeper to false
  sudo: yes
  lineinfile: dest=/etc/hbase/conf/hbase-env.sh regexp='HBASE_MANAGES_ZK' line='export HBASE_MANAGES_ZK=false'

- name: copy the hbase configuration files
  template: src={{ item }}.j2 dest=/etc/hbase/conf/{{ item }} mode=644
  with_items:
    - hbase-site.xml

- name: mkdir hbase rootdir
  sudo: yes
  shell: mkdir -p {{ cdh5_hbase_rootdir }} 

- name: chown hbase rootdir
  sudo: yes
  shell: chown hbase -R {{ cdh5_hbase_rootdir }} 

- name: mkdir hbase datadir
  sudo: yes
  shell: mkdir -p {{ cdh5_hbase_datadir }} 

- name: chown hbase datadir
  sudo: yes
  shell: chown hbase -R {{ cdh5_hbase_datadir }} 

- name: start_daemons
  service: name={{ item }} state=started
  with_items:
    - hbase-master

