- hosts: hadoop_journalnode
  gather_facts: no
  tasks:
    - name: start_daemons
      service: name={{ item }} state=started
      with_items:
        - hadoop-hdfs-journalnode
      when: ha_enabled

- hosts: hadoop_namenode
  gather_facts: no
  tasks:
    - name: start_daemons
      service: name={{ item }} state=started
      with_items:
        - hadoop-hdfs-namenode

- hosts: hadoop_namenode
  gather_facts: no
  tasks:
    - name: start_daemons
      service: name={{ item }} state=started
      with_items:
        - hadoop-hdfs-zkfc
      when: ha_enabled

- hosts: hadoop_slave
  gather_facts: no
  tasks:
    - name: start_daemons
      service: name={{ item }} state=started
      with_items:
        - hadoop-hdfs-datanode

