---
- include: webupd8.yml
- name: check jdk installed
  shell: dpkg -s {{ item }} | grep "install ok installed"
  ignore_errors: yes
  with_items: '{{ java_versions }}'
  register: check_jdk_installed
- name: Automatically select the Oracle License
  tags: java
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  when: check_jdk_installed.results[0].rc != 0
- name: Install Oracle Java
  tags: java
  apt: pkg={{ item }} update_cache=yes state=latest
  with_items: '{{ java_versions }}'
  when: check_jdk_installed.results[0].rc != 0
- name: Set JAVA_HOME
  lineinfile: line=JAVA_HOME=/usr dest=/etc/environment state=present