- name: Add the Cloudera APT repository key
  apt_key: data="{{ lookup('file', 'cloudera-repo.key') }}" state=present

- name: Add the Cloudera APT preference
  copy: src=cloudera.pref dest=/etc/apt/preferences.d/
- name: Add the Cloudera Repository
  apt_repository: repo="deb [arch=amd64] {{ repo }}" state=present

- name: Add the Cloudera src Repository
  apt_repository: repo="deb-src {{ repo }}" state=present


